openapi: 3.0.1
info:
  title: refund-api
  description: API Definition of refund-api
  version: 1.0.0
servers:
- url: http://localhost:8290/refund-api
paths:
  /:
    get:
      responses:
        default:
          description: Default response
